name: pantry
version: 0.1.0.0
# FIXME add normal stuff, ChangeLog, README.md as well

extra-source-files:
- attic/package-0.1.2.3.tar.gz

dependencies:
- base
- rio
- aeson
- text
- unordered-containers
- containers
- path
- transformers
- generic-deriving
- unliftio
- http-conduit
- http-client-tls
- http-types
- http-client
- conduit
- bytestring
- network-uri
- hackage-security
- primitive
- vector
- memory
- store
- cryptonite
- cryptonite-conduit
- persistent
- persistent-sqlite
- persistent-template
- resource-pool
- Cabal
- path-io
- rio-orphans
- conduit-extra
- tar-conduit
- time
- unix-compat
- hpack
- yaml
- zip-archive

library:
  source-dirs: src/
  exposed-modules:
  - Pantry
  - Pantry.SHA256
  - Data.Aeson.Extended

  # For testing
  - Pantry.Internal
  - Pantry.Internal.StaticBytes

flags:
  convert-old-stackage:
    description: Build the convert-old-stackage executable
    manual: true
    default: false

executables:
  # Remove this executable once we're totally switched over.
  # Keeping the src directory for now to avoid needing to expose internals.
  convert-old-stackage:
    when:
    - condition: ! '! flag(convert-old-stackage)'
      buildable: False
    source-dirs:
    - app/
    - src/
    main: convert-old-stackage.hs

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - pantry
    - hspec
    - exceptions
    - hedgehog
    - QuickCheck
