name: pantry
version: 0.1.0.0

extra-source-files:
- attic/package-0.1.2.3.tar.gz

dependencies:
- base
- rio
- aeson
- text
- unordered-containers
- containers
- path
- transformers
- generic-deriving
- unliftio
- http-conduit
- http-client-tls
- http-types
- http-client
- conduit
- bytestring
- network-uri
- hackage-security
- primitive
- vector
- memory
- store
- cryptonite
- cryptonite-conduit
- persistent
- persistent-sqlite
- persistent-template
- resource-pool
- Cabal
- path-io
- rio-orphans
- conduit-extra
- tar-conduit
- time
- unix-compat
- hpack
- yaml
- zip-archive

when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
  else:
    dependencies:
    - unix

library:
  source-dirs: src/
  exposed-modules:
  - Pantry
  # FIXME make these exports unnecessary
  - Pantry.Types
  - Pantry.StaticSHA256
  - Pantry.Storage
  - Data.Aeson.Extended
  - Pantry.StaticBytes
  other-modules:
  - Hackage.Security.Client.Repository.HttpLib.HttpClient
  - Pantry.Archive
  - Pantry.Hackage
  - Pantry.HTTP
  - Pantry.Repo
  - Pantry.Tree

executables:
  convert-old-stackage:
    source-dirs: app/
    main: convert-old-stackage.hs
    dependencies:
    - pantry
    other-modules:
    - Pantry.OldStackage

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - pantry
    - hspec
    - exceptions
    - hedgehog
