resolver: lts-11.22

extra-deps:
- http-download-0.1.0.0
- rio-orphans-0.1.1.0
- rio-prettyprint-0.1.0.0
- Cabal-2.4.1.0
- ansi-terminal-0.9@rev:0
- rio-0.1.11.0
- cabal-doctest-1.0.6
- http-api-data-0.3.8.1
- happy-1.19.9
- typed-process-0.2.6.0
- unliftio-0.2.12
- hedgehog-0.6.1 # for ansi-terminal-0.9

ghc-options:
   "$locals": -fhide-source-paths
