resolver: lts-13.28

extra-deps:
- http-download-0.1.0.0
- rio-prettyprint-0.1.0.0
- ansi-terminal-0.9
- rio-0.1.11.0
- unliftio-0.2.12

- github: fpco/casa
  commit: fe80c92fde5458d0b1521b2bc6853a5a08b0fa52
  subdirs:
     - casa-client
     - casa-types

ghc-options:
   "$locals": -fhide-source-paths
